### ISSUE TITLE
Please add standard test data/cases

### ISSUE THREAD

**Issue by LukeAFullard** [jbogalo/CiSSA#2]
Hello,
I am almost finished converting your code to a Python version and I would like to run comparison cases between the two for validation that I have ported the code correctly.
Could you please add an example data-set and results of running CiSSA with the settings used so that I can compare the codes?

Thank you.

**Comment by jbogalo** [comment]
Hello.

 

I send you an example in the attached file. I have run the code:

 

1.	[Z, psd, R, U] = cissa(x,96);
2.	[rc, sh, kg] = group(Z,psd,12);

 

Where the ‘x’ input contains the time series, electric power consumption.

The outputs of 1) are on the sheets with the red tab. The outputs of 2) are on the sheets with the green tab.

 

Best regards,

Juan Bógalo

 

 

De: LukeAFullard ***@***.***> 
Enviado el: viernes, 28 de octubre de 2022 22:24
Para: jbogalo/CiSSA ***@***.***>
CC: Subscribed ***@***.***>
Asunto: [jbogalo/CiSSA] Please add standard test data/cases (Issue #2)

 

Hello,
I am almost finished converting your code to a Python version and I would like to run comparison cases between the two for validation that I have ported the code correctly.
Could you please add an example data-set and results of running CiSSA with the settings used so that I can compare the codes?

Thank you.

**Comment by LukeAFullard** [comment]
Hi,
Sorry, but the attachment did not come through. Perhaps Github does not allow it?
Thank you
